# Generated by Django 4.2.14 on 2024-07-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_assigned_users_userrole_has_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='has_tasks',
        ),
    ]
