# Generated by Django 4.2.14 on 2024-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='default_username', max_length=20),
        ),
    ]
