# Generated by Django 4.2.14 on 2024-07-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_task_assigned_to_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
    ]
