# Generated by Django 4.2.14 on 2024-07-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('task_creator', 'Task Creator'), ('read_only', 'Read Only')], max_length=50),
        ),
    ]
